#!/usr/bin/env python3
"""Regenerate illo/assets/checksums.txt — the manifest that drives
illo/scripts/repair-hermes-assets.sh.

Each line: <sha256>  <pin-commit>  <path relative to illo/>
The pin commit is the asset's own last-change commit, so the
raw.githubusercontent.com URL it implies is immutable and survives merges.

Run with --check to verify the committed manifest is current (exit 1 if not).
Assets with uncommitted changes have no valid pin yet — that's an error here;
CI regenerates post-commit on the PR branch, where the tree is always clean.
"""
import hashlib
import pathlib
import subprocess
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
SKILL = REPO / "illo"
ASSETS = SKILL / "assets"
MANIFEST = ASSETS / "checksums.txt"
BINARY_EXTS = {".png", ".webp", ".jpg", ".jpeg", ".gif"}
HEADER = (
    "# Generated by .github/scripts/regen_asset_checksums.py — do not edit.\n"
    "# <sha256>  <pin-commit>  <path relative to illo/>\n"
)


def git(*args):
    return subprocess.run(["git", *args], cwd=REPO, check=True,
                          capture_output=True, text=True).stdout.strip()


def build_manifest():
    lines = []
    for f in sorted(ASSETS.rglob("*")):
        if not (f.is_file() and f.suffix.lower() in BINARY_EXTS):
            continue
        rel_repo = f.relative_to(REPO).as_posix()
        rel_skill = f.relative_to(SKILL).as_posix()
        dirty = subprocess.run(["git", "diff", "--quiet", "HEAD", "--", rel_repo],
                               cwd=REPO).returncode != 0
        untracked = not git("ls-files", "--", rel_repo)
        if dirty or untracked:
            sys.exit(f"ERROR: {rel_repo} has uncommitted changes — commit it first "
                     f"so its pin commit exists, then regenerate.")
        pin = git("log", "-1", "--format=%H", "--", rel_repo)
        if not pin:
            sys.exit(f"ERROR: {rel_repo} has no commit history — commit it first.")
        sha = hashlib.sha256(f.read_bytes()).hexdigest()
        lines.append(f"{sha}  {pin}  {rel_skill}\n")
    return HEADER + "".join(lines)


def main():
    want = build_manifest()
    have = MANIFEST.read_text() if MANIFEST.exists() else ""
    if "--check" in sys.argv:
        if have != want:
            sys.stderr.write("checksums.txt is stale — run "
                             ".github/scripts/regen_asset_checksums.py\n")
            sys.exit(1)
        print("checksums.txt is current")
        return
    if have == want:
        print("checksums.txt already current")
        return
    MANIFEST.write_text(want)
    print(f"wrote {MANIFEST.relative_to(REPO)}:")
    sys.stdout.write(want)


if __name__ == "__main__":
    main()
